call plug#begin('~/.local/share/nvim/plugged')

  " Misc
  Plug 'tpope/vim-repeat'
  Plug 'tpope/vim-abolish'
  Plug 'blindFS/vim-taskwarrior'
  
  " Git
  Plug 'tpope/vim-fugitive'
  Plug 'idanarye/vim-merginal'
  Plug 'gregsexton/gitv', {'on': ['Gitv']}

  " Navigation
  " Plug 'unblevable/quick-scope'
  Plug 'christoomey/vim-tmux-navigator'
  Plug 'yuttie/comfortable-motion.vim'
  Plug 'easymotion/vim-easymotion'
    " Gif config
    map  / <Plug>(easymotion-sn)
    omap / <Plug>(easymotion-tn)

    " These `n` & `N` mappings are options. You do not have to map `n` & `N` to EasyMotion.
    " Without these mappings, `n` & `N` works fine. (These mappings just provide
    " different highlight method and have some other features )
    map  n <Plug>(easymotion-next)
    map  N <Plug>(easymotion-prev)
    

  " FZF
  Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' } 
  Plug 'junegunn/fzf.vim'
    " Similarly, we can apply it to fzf#vim#grep. To use ripgrep instead of ag:
    command! -bang -nargs=* Rg
      \ call fzf#vim#grep(
      \   'rg --column --line-number --no-heading --color=always --glob "!.git/*"'.shellescape(<q-args>), 1,
      \   <bang>0 ? fzf#vim#with_preview('up:60%')
      \           : fzf#vim#with_preview('right:50%:hidden', '?'),
      \   <bang>0)
    

    " Command for git grep
    " - fzf#vim#grep(command, with_column, [options], [fullscreen])
    command! -bang -nargs=* GGrep
      \ call fzf#vim#grep('git grep --line-number '.shellescape(<q-args>), 0, <bang>0)
    
    nnoremap <leader>e :FLines<cr>

  " Airline
  Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'
    let g:airline#extensions#tabline#enabled = 1
    " let g:airline_powerline_fonts = 1
    " let g:airline_theme='dracula'
    " let g:airline_theme='quantum'

  " " File exploring
  Plug 'scrooloose/nerdtree'
  Plug 'jistr/vim-nerdtree-tabs'
    nnoremap <leader>t :NERDTreeTabsToggle<cr>
    
  " UI
  Plug 'airblade/vim-gitgutter'
    " disable default <leader>h mappings
    let g:gitgutter_map_keys = 0
    
  Plug 'junegunn/vim-peekaboo'
  Plug 'mhinz/vim-startify'
  Plug 'edkolev/tmuxline.vim'

  " Style
  Plug 'dracula/vim'
  " Plug 'joshdick/onedark.vim'
  Plug 'KeitaNakamura/neodark.vim'
  " Plug 'tyrannicaltoucan/vim-quantum'
  Plug 'nathanaelkane/vim-indent-guides'

  " Language features
  Plug 'Shougo/deoplete.nvim'
    let g:deoplete#enable_at_startup = 1
    " let g:deoplete#omni#functions = {}
    " let g:deoplete#sources = {}
    " let g:deoplete#sources._ = ['file', 'neosnippet']
    " let g:deoplete#omni#input_patterns = {}
    
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-surround'
  Plug 'jiangmiao/auto-pairs'
  Plug 'junegunn/rainbow_parentheses.vim'
  Plug 'sbdchd/neoformat'
    let g:neoformat_enabled_javascript = ['prettier']
    autocmd BufWritePre *.js,*.jsx Neoformat prettier
    
  " Plug 'w0rp/ale', { 'on': ['ALEEnable', 'ALEToggle'] }

  " Languages
  Plug 'sheerun/vim-polyglot'
    let g:polyglot_disabled = ['elm']
    
  " JAVASCRIPT
  " Base lang support from vim-polyglot
  Plug 'mxw/vim-jsx' 
  Plug 'carlitux/deoplete-ternjs'
  Plug 'ternjs/tern_for_vim', { 'do': 'npm install' }
    autocmd FileType javascript nnoremap <silent> <buffer> gb :TernDef<CR>
    let g:tern#filetypes = [
                \ 'jsx',
                \ 'javascript.jsx',
                \ 'javascript',
                \ ]
  
  Plug 'alx741/vim-hindent'
  Plug 'mattn/emmet-vim'
  
  " Elm
  Plug 'pbogut/deoplete-elm', { 'for': 'elm' }
  Plug 'ElmCast/elm-vim', { 'for': 'elm' }
    let g:elm_format_autosave = 1
    let g:elm_detailed_complete = 1
    let g:elm_syntastic_show_warnings = 1
    let g:elm_setup_keybindings = 0
    autocmd FileType elm set tabstop=4 softtabstop=4 shiftwidth=4
    " let g:elm_format_fail_silently = 1
    " let g:elm_browser_command = 'open'
    " let g:elm_make_show_warnings = 1
    " let g:deoplete#omni#functions.elm = ['elm#Complete']
    " let g:deoplete#omni#input_patterns.elm = '[^ \t]+'
    " let g:deoplete#sources.elm = ['omni'] + g:deoplete#sources._
    
  " Run last, as per devicons README
  Plug 'ryanoasis/vim-devicons'
    let g:airline_powerline_fonts = 1

call plug#end()



" Settings
set encoding=utf8
set whichwrap+=<,>,[,]
set colorcolumn=80
set expandtab
set shiftwidth=2
set softtabstop=2
set hidden

" Mouse
set mouse=a

" EDITING UI AND HIGHLIGHTING
set termguicolors
if exists('$TMUX')
  set t_Co=256
endif

colorscheme dracula
" let g:quantum_black=1
let g:neodark#background = '#202020'
set background=dark
set relativenumber
set cursorline
" guifont breaks in VimR
" set guifont=FuraCode\ Nerd\ Font\ Medium:h16


" Split tricks
set splitbelow
set splitright


" JAVASCRIPT

" Code completion settings
" deoplete tab-complete
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
" tern

" Cool conceal
let g:javascript_conceal_null = "ø"
let g:javascript_conceal_static = "@"
" let g:javascript_conceal_this = "@"

" Syntax highlighting tweaks
autocmd FileType javascript,javascript.jsx syntax match   jsFauxConstant "\<[A-Z0-9_\$]\+\>"
autocmd FileType javascript,javascript.jsx syntax cluster jsImportContainer    add=jsFauxConstant
autocmd FileType javascript,javascript.jsx syntax cluster jsDestructuringBlock add=jsFauxConstant
autocmd FileType javascript,javascript.jsx syntax cluster jsExpression         add=jsFauxConstant
autocmd FileType javascript,javascript.jsx syntax cluster jsDestructuringBlock add=jsFauxConstant

highlight link jsFuncCall Function
highlight link jsFauxConstant Boolean

" Auto Semi-colon & comma
nnoremap <leader>; me:call ToggleEndChar(';')<cr>`e
nnoremap <leader>, me:call ToggleEndChar(',')<cr>`e
inoremap <leader>; <Esc>me:call ToggleEndChar(';')<cr>`ea
inoremap <leader>, <Esc>me:call ToggleEndChar(',')<cr>`ea

function! ToggleEndChar(charToMatch)
    s/\v(.)$/\=submatch(1)==a:charToMatch ? '' : submatch(1).a:charToMatch
endfunction


" File ignores
set wildignore+=.git,.svn
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg
set wildignore+=*.sw?
set wildignore+=.DS_Store
set wildignore+=node_modules,bower_components,elm-stuff

" GUI
set laststatus=2 " fix vssim-airline not showing

" Bindings
" Fuzzy open files
noremap <leader>p :Files<cr>

" Saving, closing and quiting
inoremap <leader>w <Esc>:w<cr>
nnoremap <leader>w :w<cr>
inoremap <leader>e <Esc>:q<cr>
nnoremap <leader>e :q<cr>
nnoremap <leader>E :q!<cr>
nnoremap <leader>q :bp<bar>sp<bar>bn<bar>bd<CR><cr>

" Clear current highlighting
nnoremap <leader><esc> :noh<cr>

" Pane navigation
" map <C-j> <C-W>j
" map <C-k> <C-W>k
" map <C-h> <C-W>h
" map <C-l> <C-W>l

" Buffer switching
noremap <leader>a :bprevious<cr>
noremap <leader>l :bnext<cr>

" Finding lines of code
nnoremap <leader>ff :Lines<cr>
nnoremap <leader>fp :GGrep<cr>

" Exiting insert mode hacks
inoremap jw <Esc>
inoremap wj <Esc>

" Git Gutter
noremap <leader>ghs :GitGutterStageHunk<cr>
noremap <leader>ghu :GitGutterUndoHunk<cr>
noremap <leader>ghv :GitGutterPreviewHunk<cr>
noremap <leader>ghn :GitGutterNextHunk<cr>
noremap <leader>ghp :GitGutterPrevHunk<cr>

" Maintain indent in normal mode
inoremap <CR> <CR>x<BS>
nnoremap o ox<BS>
nnoremap O Ox<BS>

