# editors
alias l="ls -al"
alias stt="subl ."
alias ch="code ."
alias vim="vim"
alias vh="vim ."
alias vimrc="vim ~/.vimrc"
alias efc="vim ~/.config/fish/config.fish"
alias mvh="mvim ."
alias nvh="vimr -s ."
alias mvim="/Applications/MacVim.app/Contents/bin/mvim"

# npm
alias lnrd="set -lx NODE_ENV local; npm run dev"
abbr -a lnpm="set -lx NODE_ENV local; and npm"
abbr -a nr="npm run"

# git
abbr -a gco="git checkout"
alias gcm="git checkout master"
abbr -a gmb="git checkout -b"
abbr -a gbrm="git branch -d"
abbr -a gbfrm="git branch -D"
alias grhh="git reset --hard head"
alias gst="git status"
abbr -a grb="git rebase"
abbr -a grbi="git rebase -i"
alias grbm="git rebase master"
alias grbc="git rebase --continue"
alias gb="git branch"
alias gba="git branch -a"
abbr -a ga "git add"
alias gap="git add -p"
alias gc="git commit"
alias gpll="git pull -r"
alias gpshf="git push -f"
alias gpsh="git push"
alias gca="git commit --amend"
alias gcan="git commit --amend --no-edit"
alias grph="git rev-parse HEAD"
alias gl="git log --oneline --graph"
alias gd="git diff"
alias gds="git diff --staged"
